
language: java

jdk:
  - openjdk8
  - oraclejdk9

install:
  - ./gradlew clean jar

script:
  - ./gradlew test
  - ./gradlew test jacocoTestCoverageVerification

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true


