
language: java

jdk:
  - openjdk8
  - oraclejdk9

env:
  - COVERAGE=0.5 CODE=./monolithic/ui
  - COVERAGE=0.5 CODE=./monolithic/service/cart
  - COVERAGE=0.5 CODE=./monolithic/service/user

  - COVERAGE=0.5 CODE=./monolithic/repository/order
  - COVERAGE=0.5 CODE=./monolithic/repository/cart
  - COVERAGE=0.5 CODE=./monolithic/repository/product
  - COVERAGE=0.5 CODE=./monolithic/repository/user

install:
  - ./gradlew clean jar

script:
  - COVERAGE=$COVERAGE ./gradlew -p $CODE check

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true


