language: java
jdk:
- openjdk8
- oraclejdk9
env:
  global: 
  - secure: p/oPidsWKHncPpcfhFxPI10/Z4IYwQY7ZZgJn6A7RvvnB783xw8UNYC2nDS0bN1ZTBtSVy1oXAx4nkhc9gqT6mtn9rl7jc0Id0vKMlQZKVYODxF5gepcXuOKp3ChbJWHr5TqYer0Xl64+tZBFhsfPCcrTM/Mm1coBH8i6VFKnIavwHD74FHb6zABvqvQt4fMvsTozncSz6EGhQHtRfjXUfJZed1tFEnLosV66VKkclJ27s1jSg/Jo5vxeiEIkpwVgrpbx0ggXaalUWwWTZWBmvMRdrxM73vyQ6n02mMARhGuY9cgcg/Y93Aenl9eCF7mlB9XQ5TbXsfQtGuDBCoPzzpxEWrtWqvG5Yen/0QC+iu5HQvFpdxBZjDgJohLzzY/7UBba0fD87L4X8q1nShT6U13LwGucwACg7RBItlI+R59IIXq6pa43Bec78hGexRZh5qY5iUzOqKjkmqJncL6jiZYoLdDKOdk25KBhQX+qGgiB4VM+azWGO2FXlUQ7Wpe9G54psN2yKK7Y23Q//grCDVcKON44FztKcnj7JJGWdYLC1vV8L30FGmcrdCw76XpltM5i+3F2tHKxc5I0Izf6QRhykV0hih4fNkyikxsDh1P3hRSONp2lw8RjAJfkn3RPUyxu01QF2kfo5oFSIIST0ZCKgKS7mSQ1fhc7loMc8Q=
  - secure: Lf7P91T1/anwM/d+G9qjC+zfR8plk9JqGSBHs4pt00dknsGn0L0o78cblBmf4f6chaA6oRiIp54xUsyhLrX4i4Qe2DLaMESimR3PfQzfjPuoYaRVYwNjT185vjcf/5som0jkCAenjtzDRH0mcrya4NuZkPSIEoqsCHYq7ZRtlkivOKPstMO/pn9cg2SlteLSfvlAm/38OeiPCCJwoFi0Mr+plPx2QXdf3PyVoqy0rQFWovHFNxxH7pndtTWWglzpuDiksHBGsj9fN58Zp37xPWEcbZk6szijIcTJS1cguUhL3m0o4zvtZePT+NaRJnkNRz53kU8xk5wWEPA9YnHrzZ2aFxYlyPXNuqWC089HKyd/tHFAVH8Mn0YkosVxagMiQaP3+j0jczJUD+AdDM99BVKz6KQL5U/OT7aC+I+xad8i8Xaa+Oo7McvfI8MxGjV7bDrG0XX2MPPALe8McokxNeM4uFjJ7xxhcnteTU9LohDTV/nvjeTnsr5GOiYx683NWGMBA39XqGN2ljUh6fZqcCXBIDapt2H6PsWsKk6qsnx3QTDimZPFXUIPmDw6Xh0Y4vjLHYtRWS9HfBMLgwD3S/Qh4cn+Zwn9pwVYInerVpyDQsBCwqJ660hdRHZ3G79Mr8KLRU3OKump6apAfhTNaYeCb1uW0AqRB3GsMGoWZYU=
  matrix:
  - COVERAGE=0.5 CODE=./monolithic/ui
  - COVERAGE=0.5 CODE=./monolithic/service/cart
  - COVERAGE=0.5 CODE=./monolithic/service/user
  - COVERAGE=0.3 CODE=./monolithic/repository/order
  - COVERAGE=0.5 CODE=./monolithic/repository/cart
  - COVERAGE=0.5 CODE=./monolithic/repository/product
  - COVERAGE=0.3 CODE=./monolithic/repository/user
install:
- "./gradlew clean jar"
script:
- COVERAGE=$COVERAGE ./gradlew -p $CODE check
after_success:
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASS}\" | docker login --username \"${DOCKER_LOGIN}\"
    --password-stdin"
  on:
    all_branches: true
